### PR TITLE
fix: improved project card and buttons

### LINKED ISSUE #137: [FEATURE] improve project card
### Description

make it better in-terms of responsiveness and layout wise

Screenshot 2022-09-15 at 10 15 24 PM

### PR DESCRIPTION
**Pull request by rohitdasu**
### Fixes Issue

fixes #137 

### Changes proposed

* improved project card
* improved button
* updated new project image

### CODE REVIEW

File: components/Projects/Project.tsx [hunk 1]
```diff
@@ -12,35 +12,38 @@ export const Project = ({ title, description, tags, author }: ProjectProps) => {
...
+            width={innerWidth/1.2}
           />
         </div>
-        <div className="flex flex-col space-y-2 p-2">
+        <div className="h-full flex flex-col justify-between space-y-2 p-2">
           <h1 className="font-semibold text-xl">
             {title} - <span className="text-lg font-light">{author}</span>
           </h1>
-          <p className="text-[14px] ">{description}</p>
+          <p className="text-sm ">{description}</p>
```
Comment (AdityaPainuli) [inline components/Projects/Project.tsx:40]: we should put a truncate property here so that the description overflowed can be shown as ....

File: components/Projects/Project.tsx [hunk 2]
```diff
@@ -12,35 +12,38 @@ export const Project = ({ title, description, tags, author }: ProjectProps) => {
...
-        <div className="w-[250px] md:w-[500px] mx-auto h-auto p-4">
+        <div className="w-full p-2 flex justify-center items-center">
           <Image
             src={'/open-source.png'}
             alt={title}
-            height={'300'}
-            width={'300'}
-            className="object-contain  "
+            height={800}
+            width={innerWidth/1.2}
```
Comment (AdityaPainuli) [inline components/Projects/Project.tsx:33]: you should put object-contain as the image user will provide can be of  different dimensions

File: components/Projects/Project.tsx [hunk 3]
```diff
@@ -12,35 +12,38 @@ export const Project = ({ title, description, tags, author }: ProjectProps) => {
   const handleContribute = () => {
     return;
   };
+  const [innerWidth, setInnerWidth] = useState(0);
+  useEffect(() => {
```
Comment (AdityaPainuli) [inline components/Projects/Project.tsx:16]: Just curious can you explain to me what this piece of code is doing?

**Review by AdityaPainuli — CHANGES_REQUESTED** [review]

File: components/Projects/Project.tsx (hunk 3 above)
Comment (rohitdasu) [reply components/Projects/Project.tsx:16]: it's getting the width of the window. `window` is not available in Server code so i've put it in `useEffect` to make sure we get the `window` property

File: components/Projects/Project.tsx (hunk 1 above)
Comment (rohitdasu) [reply components/Projects/Project.tsx:40]: ok

File: components/Projects/Project.tsx (hunk 2 above)
Comment (rohitdasu) [reply components/Projects/Project.tsx:33]: object-cover should be best here it will cover the entire area.

Comment (AdityaPainuli) [reply components/Projects/Project.tsx:33]: yeah but what if user provide image which is not of the same dimension in that case it can look bad .

File: components/Projects/Project.tsx (hunk 3 above)
Comment (AdityaPainuli) [reply components/Projects/Project.tsx:16]: ok got it. it's a nice trick I come to know today, thanks!

File: components/Projects/Project.tsx (hunk 2 above)
Comment (rohitdasu) [reply components/Projects/Project.tsx:33]: if user uploads different dimension it will cover the entire image so it will fit to the container

**Review by leewan-09 — COMMENTED** [review]
LGTM 👍

**Review by leewan-09 — CHANGES_REQUESTED** [review]
LGTM

**Review by leewan-09 — APPROVED** [review]
