### PR TITLE
fixed sidebar

### LINKED ISSUE #416: [BUG] side nav items not active issue
### Description

when we click on any nav item it is not changing the text color to active; only icon color changes. also the icon and text alignment is not centred. fix it.

### Screenshots

Screenshot 2023-08-11 at 12 45 05 AM

### PR DESCRIPTION
**Pull request by dhruvgoyal3118**
Closes Issue https://github.com/rohitdasu/projectmate/issues/416
closes #416 
fixed styling of svg icons to align them with text 
Also in SideBar outputting span tag differently according to active state

### CODE REVIEW

**Review by rohitdasu — CHANGES_REQUESTED** [review]
please fix it

File: components/Layouts/Sidebar/data.tsx [hunk 1]
```diff
@@ -1,22 +1,33 @@
 import { FaHome, FaNewspaper, FaUserFriends } from 'react-icons/fa';
-
+const iconStyleProjects = {
```
Comment (rohitdasu) [inline components/Layouts/Sidebar/data.tsx:2]: Login/signup button icon is not same size as other icons. fix it as well. 

Screenshot 2023-08-14 at 10 39 18 PM

**Review by rohitdasu — APPROVED** [review]
